apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: gateway
  template:
    metadata:
      labels:
        component: gateway
    spec:
      containers:
        - name: gateway
          image: azsuth/beefy-gainz-gateway
          ports:
            - containerPort: 3001
          env:
            - name: GATEWAY_PORT
              value: '3001'
            - name: GATEWAY_CLIENT_UPSTREAM
              value: 'http://client-service:3000'
            - name: GATEWAY_EXERCISE_UPSTREAM
              value: 'http://exercise-service:8080'
            - name: GATEWAY_USER_ID_OVERRIDE
              value: '12345'

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    component: gateway
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30100